network_path: "metric_learning/model/rSfM120k-tl-resnet152-gem-w-f39cada.pth"
image_size: 1024 # maximum size of longer image side used for testing (default: 1024)
multiscale: "[1]" # use multiscale vectors for testing, examples: '[1]' | '[1, 1/2**(1/2), 1/2]' | '[1, 2**(1/2), 1/2**(1/2)]' (default: '[1]')