#!/bin/bash


python ./src/test_style --dataset "../../Datasets/custom/TestStyleTransfer/1 - photo" --real "../../Datasets/custom/TestStyleTransfer/4 - renaissance" --model CycleGAN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix cyclegan_renaissance --config src/style_transfer/config/cyclegan_test.yaml G_A ../../Models/CycleGAN/renaissance/latest_net_G_A.pth G_B ../../Models/CycleGAN/renaissance/latest_net_G_B.pth
python ./src/test_style --dataset "../../Datasets/custom/TestStyleTransfer/1 - photo" --real "../../Datasets/custom/TestStyleTransfer/4 - renaissance" --model AdaIN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix adain_renaissance --config src/style_transfer/config/adain.yaml vgg ../../Models/AdaIN/vgg_normalised.pth decoder ../../Models/AdaIN/decoder.pth
python ./src/test_style --dataset "../../Datasets/custom/TestStyleTransfer/1 - photo" --real "../../Datasets/custom/TestStyleTransfer/4 - renaissance" --model StarGAN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix stargan_renaissance --config src/style_transfer/config/stargan.yaml checkpoint_dir ../../Models/StarGAN style_output renaissance

python ./src/test_pose_estimation.py --data_root ../../Datasets/coco --dataset test_subset_person_keypoints_val2017 --model SWAHR --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix swahr_mixed --config src/pose_estimation/config/w48_640_test.yaml --options TEST.MODEL_FILE ../../Models/swahr/checkpoints/200_pose_higher_hrnet_coco_styled_mixed.pth
python ./src/test_pose_estimation.py --data_root ../../Datasets/HumanArt --dataset oil_painting --model SWAHR --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix swahr_mixed --config src/pose_estimation/config/w48_640_test.yaml --options TEST.MODEL_FILE ../../Models/swahr/checkpoints/200_pose_higher_hrnet_coco_styled_mixed.pth

python ./src/test_pose_estimation_on_styled_image.py --action photographicToArtistic --data_root ../../Datasets/coco --dataset test_subset_person_keypoints_val2017 --model_pose_estimation SWAHR --model_style_transfer CycleGAN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix coco__swahr_coco_mixed__cyclegan_renaissance --config_pose_estimation src/pose_estimation/config/w48_640_test.yaml --options_pose_estimation TEST.MODEL_FILE ../../Models/swahr/checkpoints/200_pose_higher_hrnet_coco_styled_mixed.pth --config_style_transfer src/style_transfer/config/cyclegan_test.yaml --options_style_transfer G_A ../../Models/CycleGAN/renaissance/latest_net_G_A.pth G_B ../../Models/CycleGAN/renaissance/latest_net_G_B.pth
python ./src/test_pose_estimation_on_styled_image.py --action photographicToArtistic --data_root ../../Datasets/coco --dataset test_subset_person_keypoints_val2017 --model_pose_estimation SWAHR --model_style_transfer AdaIN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix coco__swahr_coco_mixed__adain_renaissance --config_pose_estimation src/pose_estimation/config/w48_640_test.yaml --options_pose_estimation TEST.MODEL_FILE ../../Models/swahr/checkpoints/200_pose_higher_hrnet_coco_styled_mixed.pth --config_style_transfer src/style_transfer/config/adain.yaml --options_style_transfer vgg ../../Models/AdaIN/vgg_normalised.pth decoder ../../Models/AdaIN/decoder.pth style "../../Datasets/custom/StarGANTrainingSmall/val/4 - renaissance/15_19_titian_venus-anadyomene.jpg"
python ./src/test_pose_estimation_on_styled_image.py --action photographicToArtistic --data_root ../../Datasets/coco --dataset test_subset_person_keypoints_val2017 --model_pose_estimation ViTPose --model_style_transfer CycleGAN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix coco__vitpose_coco_mixed__cyclegan_renaissance --config_pose_estimation src/pose_estimation/config/vitpose_base_validation.py --options_pose_estimation model_file ../../Models/vitpose/coco_styled_mixed/best_coco_AP_epoch_210.pth --config_style_transfer src/style_transfer/config/cyclegan_test.yaml --options_style_transfer G_A ../../Models/CycleGAN/renaissance/latest_net_G_A.pth G_B ../../Models/CycleGAN/renaissance/latest_net_G_B.pth
python ./src/test_pose_estimation_on_styled_image.py --action photographicToArtistic --data_root ../../Datasets/coco --dataset test_subset_person_keypoints_val2017 --model_pose_estimation ViTPose --model_style_transfer AdaIN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix coco__vitpose_coco_mixed__adain_renaissance --config_pose_estimation src/pose_estimation/config/vitpose_base_validation.py --options_pose_estimation model_file ../../Models/vitpose/coco_styled_mixed/best_coco_AP_epoch_210.pth --config_style_transfer src/style_transfer/config/adain.yaml --options_style_transfer vgg ../../Models/AdaIN/vgg_normalised.pth decoder ../../Models/AdaIN/decoder.pth style "../../Datasets/custom/StarGANTrainingSmall/val/4 - renaissance/15_19_titian_venus-anadyomene.jpg"

python ./src/test_pose_estimation_on_styled_image.py --action artisticToPhotographic --data_root ../../Datasets/HumanArt --dataset oil_painting --model_pose_estimation SWAHR --model_style_transfer CycleGAN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix humanart__swahr_coco_mixed__cyclegan_renaissance --config_pose_estimation src/pose_estimation/config/w48_640_test.yaml --options_pose_estimation TEST.MODEL_FILE ../../Models/swahr/checkpoints/200_pose_higher_hrnet_coco_styled_mixed.pth --config_style_transfer src/style_transfer/config/cyclegan_test.yaml --options_style_transfer G_A ../../Models/CycleGAN/renaissance/latest_net_G_A.pth G_B ../../Models/CycleGAN/renaissance/latest_net_G_B.pth
python ./src/test_pose_estimation_on_styled_image.py --action artisticToPhotographic --data_root ../../Datasets/HumanArt --dataset oil_painting --model_pose_estimation SWAHR --model_style_transfer AdaIN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix humanart__swahr_coco_mixed__adain_renaissance --config_pose_estimation src/pose_estimation/config/w48_640_test.yaml --options_pose_estimation TEST.MODEL_FILE ../../Models/swahr/checkpoints/200_pose_higher_hrnet_coco_styled_mixed.pth --config_style_transfer src/style_transfer/config/adain.yaml --options_style_transfer vgg ../../Models/AdaIN/vgg_normalised.pth decoder ../../Models/AdaIN/decoder.pth style "../../Datasets/custom/StarGANTrainingSmall/val/4 - renaissance/15_19_titian_venus-anadyomene.jpg"
python ./src/test_pose_estimation_on_styled_image.py --action artisticToPhotographic --data_root ../../Datasets/HumanArt --dataset oil_painting --model_pose_estimation ViTPose --model_style_transfer CycleGAN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix humanart__vitpose_coco_mixed__cyclegan_renaissance --config_pose_estimation src/pose_estimation/config/vitpose_base_validation.py --options_pose_estimation model_file ../../Models/vitpose/coco_styled_mixed/best_coco_AP_epoch_210.pth --config_style_transfer src/style_transfer/config/cyclegan_test.yaml --options_style_transfer G_A ../../Models/CycleGAN/renaissance/latest_net_G_A.pth G_B ../../Models/CycleGAN/renaissance/latest_net_G_B.pth
python ./src/test_pose_estimation_on_styled_image.py --action artisticToPhotographic --data_root ../../Datasets/HumanArt --dataset oil_painting --model_pose_estimation ViTPose --model_style_transfer AdaIN --batch_size 1 --num_workers 1 --results_dir .output/metrics --results_prefix humanart__vitpose_coco_mixed__adain_renaissance --config_pose_estimation src/pose_estimation/config/vitpose_base_validation.py --options_pose_estimation model_file ../../Models/vitpose/coco_styled_mixed/best_coco_AP_epoch_210.pth --config_style_transfer src/style_transfer/config/adain.yaml --options_style_transfer vgg ../../Models/AdaIN/vgg_normalised.pth decoder ../../Models/AdaIN/decoder.pth style "../../Datasets/custom/StarGANTrainingSmall/val/4 - renaissance/15_19_titian_venus-anadyomene.jpg"